# Generated by Django 3.2.5 on 2021-07-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0003_alter_doctor_vacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='vacation',
        ),
        migrations.AddField(
            model_name='doctor',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
